services:
  db:
    image: postgres:16-alpine
    container_name: qstn-bnk-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    container_name: qstn-bnk-migrate
    depends_on:
      db:
        condition: service_healthy
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@db:5432/postgres?sslmode=disable",
      "up"
    ]
    volumes:
      - ../migrations:/migrations
    restart: "on-failure"

  app:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: qstn-bnk-app
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    ports:
      - "1606:1606"
    environment:
      CONFIG_PATH: /app/config/config.yaml

volumes:
  db_data:


