service:
  timeout: "2s"
  port: ":1606"

storage:
  host: "db"
  port: "5432"
  database: "postgres"
  password: "postgres"
  username: "postgres"
  uri: "postgresql://%s:%s@%s:%s/%s?sslmode=disable"


